# site settings

title: Nancy Luong
description: Aspiring Data Scientist | Seeking Opportunities in the Data Field | Analytical Thinker and Problem Solver
taglong: Aspiring Data Scientist | Seeking Opportunities in the Data Field | Analytical Thinker and Problem Solver
tagshort: Aspiring Data Scientist | Seeking Opportunities in the Data Field | Analytical Thinker and Problem Solver
url: https://cvless.netlify.app
baseurl: ""
permalink: pretty
repo: https://github.com/nancie151/nancie151.github.io

# author settings

author:
  name: Place Holder
  email: username@domain.com
photo: /assets/jpg/photo.jpg

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
